### ISSUE TITLE
Incorrect De Morgan’s law definition in the problems book

### ISSUE THREAD

**Issue by mihal277** [lclem/logic_course_2020-2021#2]
I think there's a small mistake in the solutions section. On page 102 the De Morgan’s law ¬(ϕ1 ∨ ϕ2) ↔ ¬ϕ1 ∨ ¬ϕ2 should be written as ¬(ϕ1 ∨ ϕ2) ↔ ¬ϕ1 ∧ ¬ϕ2.

**Comment by lclem** [comment]
that's right, thanks!
