### ISSUE TITLE
English problem in sol 1.7.3

### ISSUE THREAD

**Issue by jacekchrzaszcz** [lclem/logic_course_2020-2021#3]
English:
there exists an interpolant ψ not containing neither p nor q....
the first "not" should be removed
Typo:
Then \rho[q↦0][p↦1]⊧φ,φ[p↦q],¬(p↔r),which contradicts the assumptions.
The last formula should be ¬(p↔q)

**Comment by lclem** [comment]
absolutely, thanks!
